### ISSUE TITLE
Unnecessary flex:1 #spacer in nav

### ISSUE THREAD

**Issue by mahdiASC** [weirdochronicles/codecademy-tea-cozy#1]
The nav element can take on the flex:1 property and justify-content: flex-end to achieve the same effect in less code (and is a bit cleaner).

```css
#nav {
  color: seashell;
  padding: 25px;
  flex: 1;
  display: flex;
  justify-content: flex-end;
}
```
